name: courier_application
description: "This is a courier application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.7
  provider: ^6.1.2
  http: ^1.2.2
  google_maps_flutter_web: ^0.5.0+1
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/