// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgEFgaYRxO87Iro0DUdCjrtQyUJrXISTw',
    appId: '1:137065222350:web:1a1ec8c16acfc32e6d409f',
    messagingSenderId: '137065222350',
    projectId: 'webcourier-982ef',
    authDomain: 'webcourier-982ef.firebaseapp.com',
    storageBucket: 'webcourier-982ef.firebasestorage.app',
    measurementId: 'G-TKZFMN0JKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgEFgaYRxO87Iro0DUdCjrtQyUJrXISTw',
    appId: '1:137065222350:android:1:137065222350:android:d0ac4b9c48d611e66d409f',
    messagingSenderId: '137065222350',
    projectId: 'webcourier-982ef',
    storageBucket: 'webcourier-982ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEFgaYRxO87Iro0DUdCjrtQyUJrXISTw',
    appId: '1:137065222350:ios:your-ios-app-id',
    messagingSenderId: '137065222350',
    projectId: 'webcourier-982ef',
    storageBucket: 'webcourier-982ef.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.courierApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgEFgaYRxO87Iro0DUdCjrtQyUJrXISTw',
    appId: '1:137065222350:web:ae3188147114db676d409f',
    messagingSenderId: '137065222350',
    projectId: 'webcourier-982ef',
    authDomain: 'webcourier-982ef.firebaseapp.com',
    storageBucket: 'webcourier-982ef.firebasestorage.app',
    measurementId: 'G-F79MDYNXLM',
  );

}